import React, { FC, PropsWithChildren } from 'react';
import type { Metadata } from 'next';
import './styles/globals.css';
import CombineProviders from '@/app/_providers/CombineProviders';
export const metadata: Metadata = {
  title: 'Home',
  description: 'Generated by create next app'
};

const RootLayout: FC<PropsWithChildren> = async ({ children }) => {
  
  return (
    <html lang="en">
    <body className="!font-vazir overflow-x-hidden">
    <CombineProviders>
    { children }
    </CombineProviders>
    </body>
    </html>
  );
};

export default RootLayout;
